"use server";
import { revalidatePath } from "next/cache";
import { requireAdminSession } from "@/lib/admin/auth";
import { prisma } from "@/lib/db/prisma";
import { DEFAULT_EMAIL_TEMPLATES, type EmailTemplateType } from "@/lib/email/default-templates";
import { previewDefault } from "@/lib/email/template-service";
import { sendAndLogEmail } from "@/lib/email/email-log-service";
function can(role: string) { return ["OWNER", "ADMIN"].includes(role); }
export async function updateEmailTemplateAction(fd: FormData): Promise<void> { const actor = await requireAdminSession("/admin/email-templates"); if (!can(actor.role)) return; const id = String(fd.get("id") || ""); const current = await (prisma as any).emailTemplate.findUnique({ where: { id } }); if (!current) return; const data = { subject: String(fd.get("subject") || ""), textBody: String(fd.get("textBody") || ""), htmlBody: String(fd.get("htmlBody") || ""), enabled: fd.get("enabled") === "on", version: current.version + 1 }; await (prisma as any).emailTemplate.update({ where: { id }, data }); await (prisma as any).emailTemplateVersion.create({ data: { templateId: id, subject: data.subject, textBody: data.textBody, htmlBody: data.htmlBody, version: data.version, actorAdminId: actor.demo ? null : actor.adminId } }); revalidatePath("/admin/email-templates"); }
export async function resetEmailTemplateAction(fd: FormData): Promise<void> { const actor = await requireAdminSession("/admin/email-templates"); if (!can(actor.role)) return; const id = String(fd.get("id") || ""); const current = await (prisma as any).emailTemplate.findUnique({ where: { id } }); if (!current) return; const d = DEFAULT_EMAIL_TEMPLATES[current.type as EmailTemplateType]; const version = current.version + 1; await (prisma as any).emailTemplate.update({ where: { id }, data: { subject: d.subject, textBody: d.textBody, htmlBody: d.htmlBody, enabled: true, version } }); await (prisma as any).emailTemplateVersion.create({ data: { templateId: id, subject: d.subject, textBody: d.textBody, htmlBody: d.htmlBody, version, actorAdminId: actor.demo ? null : actor.adminId } }); revalidatePath("/admin/email-templates"); }
export async function sendTestEmailAction(fd: FormData): Promise<void> { const actor = await requireAdminSession("/admin/email-templates"); if (!can(actor.role)) return; const type = String(fd.get("type")) as EmailTemplateType; const p = previewDefault(type); await sendAndLogEmail({ type, to: actor.email, subject: `[Test] ${p.subject}`, text: p.text, html: p.html, metadata: { test: true } }); }
