import { defaultFooterText } from "@/lib/email/default-templates";
const TRUSTED_HTML = new Set(["itemsTable"]);
export type EmailTemplateLike = { subject: string; textBody: string; htmlBody: string };
export type RenderVariables = Record<string, string | number | null | undefined>;
export function escapeHtml(value: unknown) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;"); }
export function money(cents?: number | null) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format((cents || 0) / 100); }
export function itemsListFromOrder(order: any) { return (order.items || []).map((i: any) => `- ${i.quantity} × ${i.name} (${i.sku}) — ${money((i.unitPriceCents || 0) * (i.quantity || 0))}`).join("\n"); }
export function itemsTableFromOrder(order: any) { const rows = (order.items || []).map((i: any) => `<tr><td style="border-top:1px solid #e2e8f0;padding:8px">${escapeHtml(i.name)}</td><td style="border-top:1px solid #e2e8f0;padding:8px">${escapeHtml(i.sku)}</td><td style="border-top:1px solid #e2e8f0;padding:8px;text-align:right">${escapeHtml(i.quantity)}</td><td style="border-top:1px solid #e2e8f0;padding:8px;text-align:right">${escapeHtml(money((i.unitPriceCents || 0) * (i.quantity || 0)))}</td></tr>`).join(""); return `<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse"><thead><tr><th align="left">Item</th><th align="left">SKU</th><th align="right">Qty</th><th align="right">Total</th></tr></thead><tbody>${rows}</tbody></table>`; }
export function variablesFromOrder(order: any, extra: RenderVariables = {}): RenderVariables { const a = order.shippingAddress || {}; return { storeName: process.env.STORE_NAME || "Stun Fry", customerName: order.customerName || a.name || "", customerEmail: order.customerEmail || "", orderNumber: order.orderNumber || "", orderDate: order.createdAt ? new Date(order.createdAt).toLocaleDateString("en-US") : "", orderStatus: order.status || "", paymentStatus: order.paymentAttempts?.[0]?.status || order.paymentStatus || "", fulfillmentStatus: order.fulfillmentStatus || "", itemsList: itemsListFromOrder(order), itemsTable: itemsTableFromOrder(order), subtotal: money(order.subtotalCents), shipping: money(order.shippingCents), tax: money(order.taxCents), total: money(order.totalCents), shippingName: a.name || "", shippingAddress: [a.line1, a.line2].filter(Boolean).join(" "), shippingCity: a.city || "", shippingState: a.state || "", shippingZip: a.postalCode || "", carrier: order.carrier || "", trackingNumber: order.trackingNumber || "", trackingUrl: "", supportEmail: process.env.SUPPORT_EMAIL || process.env.EMAIL_REPLY_TO || "support@example.com", replyToEmail: process.env.EMAIL_REPLY_TO || process.env.SUPPORT_EMAIL || "support@example.com", footerText: defaultFooterText, ...extra }; }
function renderOne(input: string, variables: RenderVariables, html: boolean, warnings: string[]) { return input.replace(/{{\s*([a-zA-Z0-9_]+)\s*}}/g, (_m, key) => { if (!(key in variables) || variables[key] == null) { warnings.push(key); return ""; } return html && !TRUSTED_HTML.has(key) ? escapeHtml(variables[key]) : String(variables[key]); }); }
export function renderEmailTemplate(template: EmailTemplateLike, variables: RenderVariables) { const warnings: string[] = []; const subject = renderOne(template.subject, variables, false, warnings); const text = renderOne(template.textBody, variables, false, warnings); const html = renderOne(template.htmlBody, variables, true, warnings); if (warnings.length) console.warn(`Email template missing variables: ${Array.from(new Set(warnings)).join(", ")}`); return { subject, text, html, warnings: Array.from(new Set(warnings)) }; }
export function fakeOrder() { return { orderNumber: "SF-1001", createdAt: new Date("2026-07-05T12:00:00Z"), status: "PAID", fulfillmentStatus: "READY_TO_SHIP", customerName: "Jordan Buyer", customerEmail: "jordan@example.com", subtotalCents: 14800, shippingCents: 1299, taxCents: 1200, totalCents: 17299, carrier: "UPS", trackingNumber: "1Z999AA10123456784", shippingAddress: { name: "Jordan Buyer", line1: "100 Main St", city: "Seattle", state: "WA", postalCode: "98101" }, items: [{ name: "Guardian Rescue Alarm", sku: "GRA-100", quantity: 2, unitPriceCents: 2900 }, { name: "SecureWalk Training Kit", sku: "SWT-200", quantity: 1, unitPriceCents: 4900 }] }; }
