import { useState } from "react";
import { maxProductContentRows, normalProductSectionKeys } from "@/lib/products/validation";
import type { AdminProductDetail } from "@/lib/products/service";
import { Field, Select, TextArea } from "./form-controls";
import { nextProductFormKey, RepeatableList } from "./repeatable-list";
import type { SectionItem } from "./product-form-types";

export function ProductContentBlocksSection({ product }: { product?: AdminProductDetail }) {
  const overview = product?.contentSections.find((section) => section.sectionKey === "overview");
  const stateAvailability = product?.contentSections.find((section) => section.sectionKey === "state_requirements");
  const normalSections = (product?.contentSections ?? []).filter((section) => ["features_design", "comparison", "custom_section"].includes(section.sectionKey));
  const [sections, setSections] = useState<SectionItem[]>(() => normalSections.map((s, i) => ({ key: `section-${i}`, ...s })));
  const normalOffset = 2;
  return <><input type="hidden" name="contentSubmitted" value="1" /><TextArea label="Top product summary" name="description" defaultValue={product?.description} rows={3} placeholder="Compact safety device designed for responsible personal protection." hint="Brief summary shown near the top of the product page." /><input type="hidden" name="sectionKey0" value="overview" /><input type="hidden" name="sectionTitle0" value="Top product summary" /><input type="hidden" name="sectionSortOrder0" value="0" /><TextArea label="Top product summary" name="sectionBody0" defaultValue={overview?.body} rows={3} hint="Optional override for the summary next to the product media. Leave blank to use the short description." /><input type="hidden" name="sectionKey1" value="state_requirements" /><input type="hidden" name="sectionTitle1" value="State availability copy" /><input type="hidden" name="sectionSortOrder1" value="1" /><TextArea label="State availability copy" name="sectionBody1" defaultValue={stateAvailability?.body} rows={3} hint="Compliance box copy shown for restricted products." /><RepeatableList title="Normal content sections shown as page blocks" help="Add page blocks that render between the product hero and included/spec/FAQ areas. Overview, included items, specs, FAQs, and state availability have their own editors below." addLabel="+ Add content section" max={maxProductContentRows} items={sections} setItems={setSections} emptyLabel="No normal content sections yet." makeItem={() => ({ key: nextProductFormKey("section"), sectionKey: "features_design", title: product?.name ?? "Product section", editing: true, isNew: true })} summary={(item) => item.title || "Content section"}>{(item, index) => { const formIndex = normalOffset + index; return <><Select label="Section type" name={`sectionKey${formIndex}`} defaultValue={item.sectionKey ?? "features_design"} values={normalProductSectionKeys} /><Field label="Title" name={`sectionTitle${formIndex}`} defaultValue={item.title ?? product?.name} /><input type="hidden" name={`sectionSortOrder${formIndex}`} value={formIndex} /><Field label="Eyebrow" name={`sectionEyebrow${formIndex}`} defaultValue={item.eyebrow} /><label className="grid gap-2 text-sm font-bold text-slate-800 md:col-span-2">Body<textarea className="input min-h-24" name={`sectionBody${formIndex}`} defaultValue={item.body ?? ""} /></label></>; }}</RepeatableList></>;
}
