import { requireAdminSession } from "@/lib/admin/auth";
import { prisma } from "@/lib/db/prisma";
import { AdminShell, SectionHeader, StatusBadge } from "@/components/ui";
import { ClaimBatchForm, FulfillmentSettingsForm, ShipSelectedForm } from "@/components/admin/fulfillment-actions-panel";
import { getFulfillmentSettings } from "@/lib/fulfillment/admin-actions";

function groupName(date: Date) { const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const d = new Date(date); if (d >= start) return "Today"; const y = new Date(start); y.setDate(y.getDate()-1); if (d >= y) return "Yesterday"; const w = new Date(start); w.setDate(w.getDate()-7); if (d >= w) return "This week"; return "Older"; }
function fmt(date: Date) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date); }
export default async function FulfillmentPage() {
  const admin = await requireAdminSession("/admin/fulfillment");
  const settings = await getFulfillmentSettings();
  const isFulfillment = admin.role === "FULFILLMENT";
  const where = isFulfillment ? { OR: [{ assignedFulfillmentUserId: admin.adminId }, { assignedFulfillmentUserId: null, fulfillmentStatus: "READY_TO_SHIP" }] } : { OR: [{ fulfillmentStatus: { in: ["READY_TO_SHIP", "PICKING", "BLOCKED"] } }, { shippedAt: { gte: new Date(new Date().setHours(0,0,0,0)) } }] };
  const orders = await (prisma as any).order.findMany({ where: { ...where, archivedAt: null }, orderBy: { createdAt: "desc" }, take: 50, include: { shippingAddress: true, assignedFulfillmentUser: { select: { name: true, email: true } }, items: { include: { product: { select: { restricted: true } } } } } });
  const groups = ["Today", "Yesterday", "This week", "Older"].map((name) => [name, orders.filter((o: any) => groupName(o.createdAt) === name)] as const).filter(([, rows]) => rows.length);
  return <AdminShell title="Fulfillment" currentPath="/admin/fulfillment"><SectionHeader eyebrow="Shipping" title="Fulfillment dashboard">{isFulfillment ? "Assigned to me and ready-to-claim orders." : "Ready to ship, assigned, shipped today, and blocked orders."}</SectionHeader><div className="mt-6 grid gap-5 lg:grid-cols-2"><ClaimBatchForm settings={settings}/><FulfillmentSettingsForm settings={settings} canEdit={["OWNER","ADMIN"].includes(admin.role)}/></div><div className="mt-6"><ShipSelectedForm><div className="card overflow-x-auto"><table className="table"><thead><tr><th><span className="sr-only">Select</span></th><th>Order</th><th>Created</th><th>Customer</th><th>Ship to</th><th>Items</th><th>Assigned employee</th><th>Status</th></tr></thead><tbody>{groups.map(([name, rows]) => <><tr key={name}><td colSpan={8} className="bg-slate-100 font-black">{name}</td></tr>{rows.map((order: any) => { const canShip = admin.role !== "FULFILLMENT" || order.assignedFulfillmentUserId === admin.adminId; return <tr key={order.id}><td>{canShip ? <input type="checkbox" name="orderIds" value={order.id}/> : null}</td><td className="font-bold">{order.orderNumber}</td><td>{fmt(order.createdAt)}</td><td>{order.customerName || order.customerEmail || "—"}</td><td>{order.shippingAddress ? `${order.shippingAddress.state} ${order.shippingAddress.postalCode}` : "—"}</td><td>{order.items.map((i: any) => <div key={i.id}>{i.name}<br/><span className="text-xs">SKU {i.sku} · Qty {i.quantity}</span>{i.product?.restricted ? <p className="text-xs font-bold text-amber-700">Restricted: verify compliant handling.</p> : null}</div>)}</td><td>{order.assignedFulfillmentUser?.name || order.assignedFulfillmentUser?.email || "Unassigned"}</td><td><StatusBadge tone={order.fulfillmentStatus === "SHIPPED" ? "success" : order.fulfillmentStatus === "BLOCKED" ? "danger" : "warning"}>{order.fulfillmentStatus}</StatusBadge></td></tr>; })}</>)}</tbody></table>{!orders.length ? <p className="p-5 text-sm text-slate-600">No fulfillment orders match this view.</p> : null}</div></ShipSelectedForm><p className="mt-2 text-sm text-slate-600">Showing up to 50 orders.</p></div></AdminShell>;
}
