-- Phase 1 PostgreSQL foundation for the Stun Fry restricted-product prototype.
-- Safety defaults: no hard-delete path, live checkout/payment/fulfillment disabled,
-- unverified legal/compliance rules default to manual review.

CREATE TYPE "RecordStatus" AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
CREATE TYPE "AdminStatus" AS ENUM ('ACTIVE','DISABLED');
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT','ACTIVE','INACTIVE','ARCHIVED','RESTRICTED_REVIEW');
CREATE TYPE "ProductCategory" AS ENUM ('personal_safety_alarm','training','knuckle_stun_device','visibility');
CREATE TYPE "InventoryTransactionType" AS ENUM ('STOCK_IN','STOCK_OUT','ADJUSTMENT','RESERVATION','RELEASE','FULFILLMENT');
CREATE TYPE "InventoryReservationStatus" AS ENUM ('ACTIVE','RELEASED','CONSUMED','EXPIRED');
CREATE TYPE "CouponStatus" AS ENUM ('ACTIVE','INACTIVE','ARCHIVED');
CREATE TYPE "CartStatus" AS ENUM ('ACTIVE','ORDERED','ABANDONED');
CREATE TYPE "OrderStatus" AS ENUM ('DRAFT','PENDING_ELIGIBILITY','MANUAL_REVIEW','DOCUMENTS_REQUIRED','READY_FOR_PAYMENT','PAYMENT_FAILED','PAID','FULFILLMENT_HOLD','FULFILLED','CANCELLED','BLOCKED','ARCHIVED');
CREATE TYPE "PaymentProviderKind" AS ENUM ('MOCK','NMI');
CREATE TYPE "PaymentProviderStatus" AS ENUM ('DEVELOPMENT_APPROVED','MANUAL_REVIEW','DISABLED');
CREATE TYPE "PaymentAttemptStatus" AS ENUM ('NOT_STARTED','READY','APPROVED','DECLINED','FAILED','MANUAL_REVIEW');
CREATE TYPE "RefundStatus" AS ENUM ('REQUESTED','APPROVED','DECLINED','PROCESSED','FAILED');
CREATE TYPE "RuleOutcome" AS ENUM ('ALLOW','BLOCK','MANUAL_REVIEW','DOCUMENTS_REQUIRED');
CREATE TYPE "RuleReviewStatus" AS ENUM ('DRAFT','MANUAL_REVIEW','COUNSEL_REVIEW_REQUIRED','INACTIVE','ARCHIVED');
CREATE TYPE "VerificationTemplateCode" AS ENUM ('AGE_18_ATTESTATION_ONLY','AGE_18_ID_VERIFICATION','AGE_21_ID_VERIFICATION','FOID_OR_PERMIT_REQUIRED','LICENSE_TO_CARRY_OR_FIREARM_ID_REQUIRED','LOCAL_LICENSE_BACKGROUND_BRIEFING_REQUIRED','SELLER_LICENSE_OR_VOLUME_THRESHOLD_REQUIRED','BLOCKED','MANUAL_REVIEW_DEFAULT');
CREATE TYPE "VerificationRequirementType" AS ENUM ('ATTESTATION','ID_DOCUMENT','PERMIT','LOCAL_LICENSE','SELLER_LICENSE','BACKGROUND_BRIEFING','MANUAL_REVIEW','BLOCKED');
CREATE TYPE "VerificationRecordStatus" AS ENUM ('PENDING','AUTOMATIC_APPROVED','DOCUMENTS_REQUIRED','MANUAL_REVIEW','APPROVED','REJECTED','EXPIRED');
CREATE TYPE "VerificationDocumentStatus" AS ENUM ('PENDING','APPROVED','REJECTED','EXPIRED');
CREATE TYPE "AuditAction" AS ENUM ('CREATE','UPDATE','ARCHIVE','DEACTIVATE','REVIEW','APPROVE','REJECT','PAYMENT','MOCK_EVENT','SEED');
CREATE TYPE "LaunchGateStatus" AS ENUM ('DISABLED','BLOCKED','READY','ENABLED');

CREATE TABLE "AdminRole" ("id" TEXT PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "description" TEXT, "status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "MembershipTier" ("id" TEXT PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "description" TEXT, "discountBps" INTEGER NOT NULL DEFAULT 0, "status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "AdminUser" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "status" "AdminStatus" NOT NULL DEFAULT 'ACTIVE', "roleId" TEXT NOT NULL REFERENCES "AdminRole"("id"), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "name" TEXT, "status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE', "membershipTierId" TEXT REFERENCES "MembershipTier"("id"), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "Product" ("id" TEXT PRIMARY KEY, "slug" TEXT NOT NULL UNIQUE, "brand" TEXT NOT NULL, "name" TEXT NOT NULL, "category" "ProductCategory" NOT NULL, "description" TEXT NOT NULL, "status" "ProductStatus" NOT NULL DEFAULT 'DRAFT', "restricted" BOOLEAN NOT NULL DEFAULT false, "archivedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "ProductVariant" ("id" TEXT PRIMARY KEY, "productId" TEXT NOT NULL REFERENCES "Product"("id"), "sku" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "priceCents" INTEGER NOT NULL, "status" "ProductStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "ProductImage" ("id" TEXT PRIMARY KEY, "productId" TEXT NOT NULL REFERENCES "Product"("id"), "url" TEXT NOT NULL, "alt" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "ProductFeature" ("id" TEXT PRIMARY KEY, "productId" TEXT NOT NULL REFERENCES "Product"("id"), "code" TEXT NOT NULL, "label" TEXT NOT NULL, "value" TEXT NOT NULL, "restrictedRelevant" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), UNIQUE("productId","code"));
CREATE TABLE "Inventory" ("id" TEXT PRIMARY KEY, "variantId" TEXT NOT NULL UNIQUE REFERENCES "ProductVariant"("id"), "onHand" INTEGER NOT NULL DEFAULT 0, "reserved" INTEGER NOT NULL DEFAULT 0, "reorderThreshold" INTEGER NOT NULL DEFAULT 0, "status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "InventoryTransaction" ("id" TEXT PRIMARY KEY, "inventoryId" TEXT NOT NULL REFERENCES "Inventory"("id"), "type" "InventoryTransactionType" NOT NULL, "quantity" INTEGER NOT NULL, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "InventoryReservation" ("id" TEXT PRIMARY KEY, "inventoryId" TEXT NOT NULL REFERENCES "Inventory"("id"), "cartItemId" TEXT, "orderItemId" TEXT, "quantity" INTEGER NOT NULL, "status" "InventoryReservationStatus" NOT NULL DEFAULT 'ACTIVE', "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "Coupon" ("id" TEXT PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "description" TEXT, "percentOff" INTEGER, "amountOffCents" INTEGER, "status" "CouponStatus" NOT NULL DEFAULT 'ACTIVE', "startsAt" TIMESTAMP, "endsAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "Cart" ("id" TEXT PRIMARY KEY, "userId" TEXT REFERENCES "User"("id"), "status" "CartStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "CartItem" ("id" TEXT PRIMARY KEY, "cartId" TEXT NOT NULL REFERENCES "Cart"("id"), "productId" TEXT NOT NULL REFERENCES "Product"("id"), "variantId" TEXT NOT NULL REFERENCES "ProductVariant"("id"), "quantity" INTEGER NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY, "orderNumber" TEXT NOT NULL UNIQUE, "userId" TEXT REFERENCES "User"("id"), "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_ELIGIBILITY', "subtotalCents" INTEGER NOT NULL DEFAULT 0, "shippingCents" INTEGER NOT NULL DEFAULT 0, "taxCents" INTEGER NOT NULL DEFAULT 0, "totalCents" INTEGER NOT NULL DEFAULT 0, "liveCheckoutEnabled" BOOLEAN NOT NULL DEFAULT false, "liveFulfillmentEnabled" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "OrderItem" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL REFERENCES "Order"("id"), "productId" TEXT NOT NULL REFERENCES "Product"("id"), "variantId" TEXT NOT NULL REFERENCES "ProductVariant"("id"), "name" TEXT NOT NULL, "sku" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unitPriceCents" INTEGER NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "ShippingAddress" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL UNIQUE REFERENCES "Order"("id"), "name" TEXT NOT NULL, "line1" TEXT NOT NULL, "line2" TEXT, "city" TEXT NOT NULL, "state" TEXT NOT NULL, "postalCode" TEXT NOT NULL, "country" TEXT NOT NULL DEFAULT 'US', "county" TEXT, "normalized" BOOLEAN NOT NULL DEFAULT false, "deliverable" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "PaymentAttempt" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL REFERENCES "Order"("id"), "provider" "PaymentProviderKind" NOT NULL, "providerStatus" "PaymentProviderStatus" NOT NULL DEFAULT 'DISABLED', "status" "PaymentAttemptStatus" NOT NULL DEFAULT 'NOT_STARTED', "amountCents" INTEGER NOT NULL, "livePaymentEnabled" BOOLEAN NOT NULL DEFAULT false, "providerReference" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "Refund" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL REFERENCES "Order"("id"), "amountCents" INTEGER NOT NULL, "reason" TEXT NOT NULL, "status" "RefundStatus" NOT NULL DEFAULT 'REQUESTED', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "CouponRedemption" ("id" TEXT PRIMARY KEY, "couponId" TEXT NOT NULL REFERENCES "Coupon"("id"), "userId" TEXT REFERENCES "User"("id"), "orderId" TEXT REFERENCES "Order"("id"), "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "StateRestrictionRule" ("id" TEXT PRIMARY KEY, "stateCode" TEXT NOT NULL, "productCategory" "ProductCategory" NOT NULL, "productId" TEXT REFERENCES "Product"("id"), "outcome" "RuleOutcome" NOT NULL DEFAULT 'MANUAL_REVIEW', "reviewStatus" "RuleReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW', "reason" TEXT NOT NULL, "effectiveFrom" TIMESTAMP NOT NULL DEFAULT now(), "effectiveTo" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP, UNIQUE("stateCode","productCategory","productId"));
CREATE TABLE "LocalRestrictionRule" ("id" TEXT PRIMARY KEY, "stateCode" TEXT NOT NULL, "localityType" TEXT NOT NULL, "localityName" TEXT NOT NULL, "productCategory" "ProductCategory" NOT NULL, "productId" TEXT REFERENCES "Product"("id"), "outcome" "RuleOutcome" NOT NULL DEFAULT 'MANUAL_REVIEW', "reviewStatus" "RuleReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW', "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "ProductFeatureRestrictionRule" ("id" TEXT PRIMARY KEY, "productId" TEXT NOT NULL REFERENCES "Product"("id"), "featureCode" TEXT NOT NULL, "outcome" "RuleOutcome" NOT NULL DEFAULT 'MANUAL_REVIEW', "reviewStatus" "RuleReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW', "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "VerificationTemplate" ("id" TEXT PRIMARY KEY, "code" "VerificationTemplateCode" NOT NULL UNIQUE, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "status" "RecordStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "VerificationRequirement" ("id" TEXT PRIMARY KEY, "templateId" TEXT NOT NULL REFERENCES "VerificationTemplate"("id"), "type" "VerificationRequirementType" NOT NULL, "label" TEXT NOT NULL, "required" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "StateVerificationRule" ("id" TEXT PRIMARY KEY, "stateCode" TEXT NOT NULL, "productCategory" "ProductCategory" NOT NULL, "templateId" TEXT NOT NULL REFERENCES "VerificationTemplate"("id"), "reviewStatus" "RuleReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW', "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP, UNIQUE("stateCode","productCategory"));
CREATE TABLE "LocalVerificationRule" ("id" TEXT PRIMARY KEY, "stateCode" TEXT NOT NULL, "localityType" TEXT NOT NULL, "localityName" TEXT NOT NULL, "productCategory" "ProductCategory" NOT NULL, "templateId" TEXT NOT NULL REFERENCES "VerificationTemplate"("id"), "reviewStatus" "RuleReviewStatus" NOT NULL DEFAULT 'MANUAL_REVIEW', "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "archivedAt" TIMESTAMP);
CREATE TABLE "BuyerVerificationRecord" ("id" TEXT PRIMARY KEY, "userId" TEXT REFERENCES "User"("id"), "status" "VerificationRecordStatus" NOT NULL DEFAULT 'PENDING', "stateCode" TEXT, "productCategory" "ProductCategory", "automatedFirst" BOOLEAN NOT NULL DEFAULT true, "decisionReason" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP);
CREATE TABLE "BuyerVerificationDocument" ("id" TEXT PRIMARY KEY, "verificationRecordId" TEXT NOT NULL REFERENCES "BuyerVerificationRecord"("id"), "documentType" TEXT NOT NULL, "fileKey" TEXT NOT NULL, "status" "VerificationDocumentStatus" NOT NULL DEFAULT 'PENDING', "reviewerNote" TEXT, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "OrderVerificationSnapshot" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL UNIQUE REFERENCES "Order"("id"), "outcome" "RuleOutcome" NOT NULL, "templateCode" "VerificationTemplateCode" NOT NULL, "stateCode" TEXT NOT NULL, "reasons" JSONB NOT NULL, "liveCheckoutEnabled" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY, "actorAdminId" TEXT REFERENCES "AdminUser"("id"), "action" "AuditAction" NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "note" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "LaunchGate" ("id" TEXT PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "status" "LaunchGateStatus" NOT NULL DEFAULT 'DISABLED', "ownerOnly" BOOLEAN NOT NULL DEFAULT true, "liveCheckoutEnabled" BOOLEAN NOT NULL DEFAULT false, "livePaymentEnabled" BOOLEAN NOT NULL DEFAULT false, "liveFulfillmentEnabled" BOOLEAN NOT NULL DEFAULT false, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());

CREATE INDEX "Product_category_status_idx" ON "Product"("category", "status");
CREATE INDEX "StateRestrictionRule_state_category_idx" ON "StateRestrictionRule"("stateCode", "productCategory");
CREATE INDEX "Inventory_variant_idx" ON "Inventory"("variantId");
