import Link from "next/link";
import { money } from "@/lib/utils";
import { AppShell, SectionHeader, RestrictedProductBadge, StatusBadge } from "@/components/ui";
import type { CatalogProduct } from "@/lib/db/catalog";

function Card({ p }: { p: CatalogProduct }) {
  return <article className="card p-5"><div className="mb-3 h-32 rounded-xl bg-gradient-to-br from-slate-100 to-stone-200" aria-hidden="true"/><div className="flex flex-wrap gap-2">{p.restricted&&<RestrictedProductBadge/>}<StatusBadge tone={p.stock>20?"success":"warning"}>{p.stock} in stock</StatusBadge></div><h2 className="mt-3 text-lg font-black">{p.name}</h2><p className="mt-2 text-sm text-slate-600">{p.description}</p><div className="mt-4 flex items-center justify-between"><strong>{money(p.price)}</strong><Link className="btn btn-primary" href={`/products/${p.slug}`}>View</Link></div></article>;
}
function Grid({ products }: { products: CatalogProduct[] }) { return <section className="grid gap-4 md:col-span-3 md:grid-cols-2 xl:grid-cols-3">{products.map((p)=><Card p={p} key={p.id}/>)}</section>; }
export const ProductCard={Card,Grid};export { AppShell, SectionHeader };
export function ProductDetail({ product }: { product: CatalogProduct }) { return <div className="grid gap-6 md:grid-cols-2"><div className="card h-96 bg-gradient-to-br from-slate-100 to-stone-200"/><section><div className="flex flex-wrap gap-2">{product.restricted&&<RestrictedProductBadge/>}<StatusBadge tone="info">SKU {product.sku}</StatusBadge><StatusBadge tone="neutral">{product.brand}</StatusBadge></div><h1 className="mt-4 text-4xl font-black">{product.name}</h1><p className="mt-3 text-slate-600">{product.description}</p><p className="mt-5 text-3xl font-black">{money(product.price)}</p>{product.features.length>0&&<section className="mt-5 rounded-2xl border border-stone-200 bg-white p-4"><h2 className="font-black">Seeded product features</h2><ul className="mt-2 list-disc pl-5 text-sm text-slate-600">{product.features.map((feature)=><li key={feature.code}><strong>{feature.label}:</strong> {feature.value}</li>)}</ul></section>}{product.restricted&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-black">Restricted-product notice</h2><p className="mt-1 text-sm">Eligibility depends on destination law, verified address, buyer attestations, and possible document/manual review. Payment is collected only after approval. Missing or unverified rules default to manual review.</p></div>}<div className="mt-6 flex gap-3"><Link className="btn btn-primary" href="/cart">Add to cart</Link><Link className="btn btn-secondary" href="/checkout">Start checkout</Link></div></section></div>; }
