import Link from "next/link";
import { cn } from "@/lib/utils";
import { checkoutCases, complianceRules, launchGates, auditLogs, type StatusTone } from "@/lib/mock-data";
import type { RuleCoverageRow } from "@/lib/db/catalog";
export function StatusBadge({ children, tone="neutral" }: { children: React.ReactNode; tone?: StatusTone }) { const map={neutral:"bg-slate-100 text-slate-800 border-slate-200",success:"bg-emerald-50 text-emerald-800 border-emerald-200",warning:"bg-amber-50 text-amber-900 border-amber-200",danger:"bg-red-50 text-red-800 border-red-200",info:"bg-blue-50 text-blue-800 border-blue-200"}; return <span className={cn("badge",map[tone])}>{children}</span>; }
export function SectionHeader({ eyebrow,title,children }: {eyebrow?:string;title:string;children?:React.ReactNode}) { return <header className="mb-6"><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-900">{eyebrow}</p><h1 className="text-3xl font-black tracking-tight md:text-4xl">{title}</h1>{children&&<p className="mt-3 max-w-3xl text-slate-600">{children}</p>}</header>; }
export function AlertPanel({ title, children, tone="info" }: {title:string;children:React.ReactNode;tone?:StatusTone}) { const map={info:"border-blue-200 bg-blue-50",warning:"border-amber-200 bg-amber-50",danger:"border-red-200 bg-red-50",success:"border-emerald-200 bg-emerald-50",neutral:"border-slate-200 bg-slate-50"}; return <section className={cn("rounded-2xl border p-4",map[tone])} role="status"><h2 className="font-black">{title}</h2><div className="mt-1 text-sm text-slate-700">{children}</div></section>; }
export function EmptyState({ title, children }: {title:string;children:React.ReactNode}) { return <div className="card p-8 text-center"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-slate-600">{children}</p></div>; }
export function FormField({ label, value, hint, type="text" }: {label:string;value?:string;hint?:string;type?:string}) { return <label className="block text-sm font-bold">{label}<input className="input mt-2 focus-ring" defaultValue={value} type={type}/>{hint&&<span className="mt-1 block text-xs font-normal text-slate-500">{hint}</span>}</label>; }
export function StoreHeader(){return <header className="border-b border-stone-200 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><Link className="text-xl font-black" href="/">CivicGuard</Link><nav className="flex gap-4 text-sm font-bold"><Link href="/products">Products</Link><Link href="/cart">Cart</Link><Link href="/account">Account</Link><Link href="/restricted-products-policy">Restricted policy</Link></nav></div></header>}
export function StoreFooter(){return <footer className="mt-16 border-t border-stone-200 bg-white"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-8 text-sm text-slate-600 md:grid-cols-4"><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/shipping-policy">Shipping policy</Link><Link href="/returns-policy">Returns policy</Link></div></footer>}
export function AppShell({children}:{children:React.ReactNode}){return <><StoreHeader/><main className="mx-auto max-w-7xl px-4 py-8">{children}</main><StoreFooter/></>}
export function RestrictedProductBadge(){return <StatusBadge tone="warning">Restricted product · verification required</StatusBadge>}
export function CheckoutStepper({active=1}:{active?:number}){const steps=["Cart review","Shipping address","Address validation","Compliance","Documents","Totals","Hosted payment","Confirmation"];return <ol className="grid gap-2 md:grid-cols-4 lg:grid-cols-8" aria-label="Checkout progress">{steps.map((s,i)=><li key={s} className={cn("rounded-xl border p-3 text-xs font-black",i+1===active?"border-teal-800 bg-teal-50":i+1<active?"border-emerald-300 bg-emerald-50":"border-stone-200 bg-white")}><span className="block">Step {i+1}</span>{s}</li>)}</ol>}
export function CheckoutSummary(){return <aside className="card p-5"><h2 className="text-lg font-black">Order summary</h2><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>$148.00</dd></div><div className="flex justify-between"><dt>Shipping</dt><dd>$12.00</dd></div><div className="flex justify-between"><dt>Estimated tax</dt><dd>$11.84</dd></div><div className="flex justify-between border-t pt-3 text-lg font-black"><dt>Total</dt><dd>$171.84</dd></div></dl><p className="mt-4 text-xs text-slate-500">No payment is collected until compliance and verification are approved.</p></aside>}
export function ComplianceResultPanel({outcome}:{outcome:keyof typeof checkoutCases}){const c=checkoutCases[outcome]; const tone=outcome==="blocked"?"danger":outcome.includes("pending")?"warning":outcome==="paid"||outcome==="ready_for_payment"||outcome==="allowed"?"success":"danger";return <AlertPanel title={c.title} tone={tone as StatusTone}><p>{c.reason}</p><p className="mt-2"><strong>Destination:</strong> {c.state} · <strong>Payment:</strong> {c.payment} · <strong>Verification:</strong> {c.verification}</p>{outcome==="blocked"&&<p className="mt-2 font-bold">Payment button hidden because this shipment is not eligible.</p>}</AlertPanel>}
export function VerificationRequirementList(){return <ul className="list-disc space-y-2 pl-5 text-sm"><li>Confirm purchaser is at least 18 years old.</li><li>Acknowledge restricted-product policy and destination-law review.</li><li>Use verified shipping address; freight forwarding is not allowed in this prototype.</li><li>Submit documents if the state rule requires manual document review.</li></ul>}
export function DocumentUploadCard(){return <section className="card p-5"><h2 className="text-xl font-black">Required document upload</h2><p className="mt-2 text-sm text-slate-600">Upload Government ID and proof of residence. Payment remains unavailable until review is approved.</p><div className="mt-4 rounded-2xl border-2 border-dashed border-stone-300 bg-stone-50 p-8 text-center"><button className="btn btn-secondary focus-ring">Choose files</button><p className="mt-2 text-xs text-slate-500">PDF, PNG, or JPG · mock upload only</p></div><StatusBadge tone="warning">Document review pending</StatusBadge></section>}
export function OrderStatusTimeline({paid=false}:{paid?:boolean}){const items=["Address validated","Compliance checked","Documents reviewed",paid?"Payment paid":"Payment not collected","Fulfillment pending"];return <ol className="space-y-3">{items.map((x,i)=><li className="flex gap-3" key={x}><span className="badge bg-white">{i+1}</span><span>{x}</span></li>)}</ol>}
export function AdminSidebar(){const links=["/admin","/admin/products","/admin/inventory","/admin/orders","/admin/verification-queue","/admin/document-review","/admin/compliance-rules","/admin/verification-templates","/admin/rule-coverage","/admin/launch-gates","/admin/audit-log","/admin/backups"];return <aside className="admin-sidebar border-r border-stone-200 bg-slate-950 p-4 text-white md:min-h-screen"><Link href="/admin" className="text-xl font-black">CivicGuard Admin</Link><nav className="mt-6 grid gap-1 text-sm">{links.map(l=><Link className="rounded-lg px-3 py-2 hover:bg-white/10 focus-ring" href={l} key={l}>{l.replace('/admin','Admin home').replaceAll('-',' ')}</Link>)}</nav></aside>}
export function AdminHeader({title}:{title:string}){return <header className="border-b border-stone-200 bg-white p-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-black">{title}</h1><StatusBadge tone="info">Prototype · mock data</StatusBadge></div></header>}
export function AdminShell({title,children}:{title:string;children:React.ReactNode}){return <div className="admin-grid"><AdminSidebar/><div><AdminHeader title={title}/><main className="p-4 md:p-6">{children}</main></div></div>}
export function AdminDataTable({columns,rows}:{columns:string[];rows:Array<Array<React.ReactNode>>}){return <div className="card overflow-x-auto"><div className="flex gap-3 border-b p-4"><input className="input max-w-xs" aria-label="Search table" placeholder="Search"/><select className="input max-w-48" aria-label="Filter status"><option>All statuses</option><option>Pending</option><option>Blocked</option></select></div><table className="table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function RuleCoverageMatrix({ rows }: { rows?: RuleCoverageRow[] }){const data=rows??complianceRules.map(r=>({state:r.state,category:r.category,outcome:r.outcome,coverage:r.coverage,note:r.note}));return <AdminDataTable columns={["State","Category","Coverage","Outcome","Launch impact"]} rows={data.map(r=>[r.state,r.category,<StatusBadge key={`${r.state}-${r.category}`} tone={r.coverage==="covered"?"success":r.coverage==="missing"?"danger":"warning"}>{r.coverage}</StatusBadge>,r.outcome,r.note])}/>}
export function LaunchGateCard(){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{launchGates.map(g=><section className="card p-5" key={g.name}><div className="flex justify-between gap-3"><h2 className="font-black">{g.name}</h2><StatusBadge tone={g.state==="blocked"?"danger":g.state==="ready"?"warning":"success"}>{g.state}</StatusBadge></div><p className="mt-3 text-sm text-slate-600">{g.ownerOnly?"Owner-only gate. Enable action requires all blockers cleared.":"Operational gate visible to admins."}</p><button className="btn btn-secondary mt-4 focus-ring" disabled={g.state==="blocked"}>{g.state==="enabled"?"Enabled":"Review gate"}</button></section>)}</div>}
export function AuditLogTable(){return <AdminDataTable columns={["Time","Actor","Action","Target","Required note"]} rows={auditLogs.map(a=>[a.time,a.actor,a.action,a.target,a.note])}/>}
export function ConfirmDialog(){return <div className="rounded-2xl border border-red-200 bg-red-50 p-4"><h2 className="font-black">Confirmation required</h2><p className="text-sm">Dangerous actions require a keyboard-accessible confirmation dialog and a written reason in the implemented product.</p><button className="btn btn-danger mt-3 focus-ring">Confirm mock action</button></div>}
