ALTER TABLE "ProductCategory" ADD COLUMN IF NOT EXISTS "taxCode" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "taxCode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "taxProvider" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "taxCalculationId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "taxSnapshot" JSONB;
