ALTER TYPE "ProductMediaType" ADD VALUE IF NOT EXISTS 'YOUTUBE';
ALTER TABLE "ProductMedia" ADD COLUMN IF NOT EXISTS "youtubeVideoId" TEXT;
ALTER TABLE "HomepageMedia" ADD COLUMN IF NOT EXISTS "youtubeVideoId" TEXT;
