"use client";

import Link from "next/link";
import { useActionState } from "react";
import { AlertPanel } from "@/components/common/panels";
import { createProductAction, updateProductAction, type ProductActionState } from "@/lib/products/actions";
import { maxProductContentRows, maxProductFAQRows, maxProductIncludedRows, maxProductMediaRows, maxProductSpecRows, productSectionKeys, productStatuses, restrictedClassOptions } from "@/lib/products/validation";
import type { AdminProductDetail } from "@/lib/products/service";

function Field({ label, name, defaultValue, type = "text", hint }: { label: string; name: string; defaultValue?: string | number; type?: string; hint?: string }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<input className="input" name={name} defaultValue={defaultValue} type={type} />{hint ? <span className="text-xs font-medium text-slate-500">{hint}</span> : null}</label>;
}
function TextArea({ label, name, defaultValue, rows = 4 }: { label: string; name: string; defaultValue?: string; rows?: number }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<textarea className="input" rows={rows} name={name} defaultValue={defaultValue} /></label>;
}
function Select({ label, name, defaultValue, values }: { label: string; name: string; defaultValue?: string; values: readonly string[] }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<select className="input" name={name} defaultValue={defaultValue}>{values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>;
}
function FormSection({ title, description, children, open = true }: { title: string; description?: string; children: React.ReactNode; open?: boolean }) {
  return <details className="card p-5" open={open}><summary className="cursor-pointer text-lg font-black text-slate-950">{title}</summary>{description ? <p className="mt-2 text-sm text-slate-600">{description}</p> : null}<div className="mt-5 grid gap-4 md:grid-cols-2">{children}</div></details>;
}
function MediaRows({ product }: { product?: AdminProductDetail }) {
  const mediaRows = product?.media ?? [];
  return <div className="grid gap-4 md:col-span-2">{Array.from({ length: maxProductMediaRows }, (_, index) => { const media = mediaRows[index]; const isYoutube = media?.type === "YOUTUBE"; return <div className="grid gap-3 rounded-2xl border border-stone-200 p-3 md:grid-cols-4" key={index}><input type="hidden" name={`mediaType${index}`} value={isYoutube ? "YOUTUBE" : "IMAGE"} /><label className="grid gap-2 text-sm font-bold text-slate-800 md:col-span-2">Image URL<input className="input" name={`mediaUrl${index}`} defaultValue={isYoutube ? "" : media?.url} /><span className="text-center text-xs font-black uppercase text-slate-500">or upload product image</span><input className="input" name={`mediaUpload${index}`} type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" /></label><label className="grid gap-2 text-sm font-bold text-slate-800 md:col-span-2">YouTube video URL<input className="input" name={`mediaYoutubeUrl${index}`} defaultValue={isYoutube ? media?.url : ""} placeholder="https://www.youtube.com/watch?v=..." /><span className="text-xs font-medium text-slate-500">Normal YouTube and youtu.be links are supported. Video files are not uploaded.</span></label><Field label="Thumbnail URL" name={`mediaThumbnailUrl${index}`} defaultValue={media?.thumbnailUrl} /><Field label="Alt text" name={`mediaAlt${index}`} defaultValue={media?.alt} /><Field label="Title / aria label" name={`mediaTitle${index}`} defaultValue={media?.title} /><Field label="Sort order" name={`mediaSortOrder${index}`} defaultValue={media?.sortOrder ?? index} type="number" /></div>; })}</div>;
}
function ContentRows({ product }: { product?: AdminProductDetail }) {
  const sections = product?.contentSections ?? [], included = product?.includedItems ?? [], specs = product?.specs ?? [], faqs = product?.faqs ?? [];
  return <div className="grid gap-6 md:col-span-2"><TextArea label="Short description" name="description" defaultValue={product?.description} rows={3} />
    <details className="rounded-2xl border border-stone-200 p-4" open><summary className="font-black">Long description sections</summary>{Array.from({ length: maxProductContentRows }, (_, index) => { const row = sections[index]; return <div className="mt-3 grid gap-3 rounded-2xl bg-stone-50 p-3 md:grid-cols-4" key={index}><Select label="Section" name={`sectionKey${index}`} defaultValue={row?.sectionKey ?? productSectionKeys[index] ?? "overview"} values={productSectionKeys} /><Field label="Title" name={`sectionTitle${index}`} defaultValue={row?.title} /><Field label="Sort" name={`sectionSortOrder${index}`} defaultValue={row?.sortOrder ?? index} type="number" /><Field label="Eyebrow" name={`sectionEyebrow${index}`} defaultValue={row?.eyebrow} /><label className="grid gap-2 text-sm font-bold text-slate-800 md:col-span-4">Body<textarea className="input min-h-24" name={`sectionBody${index}`} defaultValue={row?.body} /></label></div>; })}</details>
    <details className="rounded-2xl border border-stone-200 p-4"><summary className="font-black">Features</summary><div className="mt-3 grid gap-3">{[0,1,2,3,4].map((index)=>{const f=product?.features?.[index]; return <div className="grid gap-3 md:grid-cols-4" key={index}><Field label="Internal code" name={`featureCode${index}`} defaultValue={f?.code}/><Field label="Label" name={`featureLabel${index}`} defaultValue={f?.label}/><Field label="Value" name={`featureValue${index}`} defaultValue={f?.value}/><label className="flex items-end gap-2 pb-3 text-sm font-bold"><input defaultChecked={f?.restrictedRelevant} name={`featureRestricted${index}`} type="checkbox" />Restricted review</label></div>;})}</div></details>
    <details className="rounded-2xl border border-stone-200 p-4"><summary className="font-black">Included items</summary>{Array.from({ length: maxProductIncludedRows }, (_, index) => { const row = included[index]; return <div className="mt-3 grid gap-3 md:grid-cols-4" key={index}><Field label="Label" name={`includedLabel${index}`} defaultValue={row?.label} /><Field label="Description" name={`includedDescription${index}`} defaultValue={row?.description} /><Field label="Quantity" name={`includedQuantity${index}`} defaultValue={row?.quantity ?? 1} type="number" /><Field label="Sort" name={`includedSortOrder${index}`} defaultValue={row?.sortOrder ?? index} type="number" /></div>; })}</details>
    <details className="rounded-2xl border border-stone-200 p-4"><summary className="font-black">Specifications</summary>{Array.from({ length: maxProductSpecRows }, (_, index) => { const row = specs[index]; return <div className="mt-3 grid gap-3 md:grid-cols-4" key={index}><Field label="Group" name={`specGroup${index}`} defaultValue={row?.group} /><Field label="Label" name={`specLabel${index}`} defaultValue={row?.label} /><Field label="Value" name={`specValue${index}`} defaultValue={row?.value} /><Field label="Sort" name={`specSortOrder${index}`} defaultValue={row?.sortOrder ?? index} type="number" /></div>; })}</details>
    <details className="rounded-2xl border border-stone-200 p-4"><summary className="font-black">FAQ</summary>{Array.from({ length: maxProductFAQRows }, (_, index) => { const row = faqs[index]; return <div className="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]" key={index}><Field label="Question" name={`faqQuestion${index}`} defaultValue={row?.question} /><Field label="Answer" name={`faqAnswer${index}`} defaultValue={row?.answer} /><Field label="Sort" name={`faqSortOrder${index}`} defaultValue={row?.sortOrder ?? index} type="number" /></div>; })}</details></div>;
}
export function ProductForm({ product, categories = [] }: { product?: AdminProductDetail; categories?: Array<{ id: string; name: string; slug: string }> }) {
  const [state, formAction] = useActionState<ProductActionState, FormData>(product ? updateProductAction : createProductAction, {});
  return <form action={formAction} encType="multipart/form-data" className="grid gap-6">{product ? <input name="id" type="hidden" value={product.id} /> : null}<AlertPanel title="Dangerous product changes require notes" tone="warning">Archive actions and restricted-status changes are audit logged. Use ARCHIVED instead of hard delete.</AlertPanel>{state.error ? <AlertPanel title="Product change blocked" tone="danger">{state.error}</AlertPanel> : null}{state.success ? <AlertPanel title="Product saved" tone="success">{state.success}</AlertPanel> : null}
    <FormSection title="Basic product info" description="Required identifiers and merchandising status stay at the top."><Field label="Name" name="name" defaultValue={product?.name} /><Field label="Slug" name="slug" defaultValue={product?.slug} /><Field label="SKU" name="sku" defaultValue={product?.sku} /><label className="grid gap-2 text-sm font-bold text-slate-800">Category<select className="input" name="categoryId" defaultValue={product?.categoryId ?? ""}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><Select label="Status" name="status" defaultValue={product?.status ?? "DRAFT"} values={productStatuses} /><Field label="Brand" name="brand" defaultValue={product?.brand ?? "Stun Fry"} /></FormSection>
    <FormSection title="Pricing and inventory"><Field label="Price" name="price" defaultValue={product?.price?.toFixed(2)} type="number" /><Field label="Stock quantity" name="stockQuantity" defaultValue={product?.stock ?? 0} type="number" /><Field label="Low stock threshold" name="lowStockThreshold" defaultValue={0} type="number" /></FormSection>
    <FormSection title="Compliance" description="Use STUN_GUN for stun-gun products; do not use legacy knuckle categories or restricted classes."><label className="flex items-center gap-2 text-sm font-bold"><input defaultChecked={product?.restricted} name="restricted" type="checkbox" />Restricted product</label><Select label="Restricted class" name="restrictedClass" defaultValue={product?.restrictedClass ?? "STUN_GUN"} values={restrictedClassOptions} /><AlertPanel title="Age and destination checks" tone="warning">Restricted products require the buyer to be at least 18 and pass state/destination verification at checkout. Existing compliance coverage is maintained by restricted class.</AlertPanel></FormSection>
    <FormSection title="Product media" description="Keep image uploads for photos and add YouTube URLs for embeds. Video file uploads are intentionally disabled for now." open={false}><MediaRows product={product} /></FormSection>
    <FormSection title="Product page content" description="Optional content is organized into collapsible panels so required fields stay clear." open={false}><ContentRows product={product} /></FormSection>
    <FormSection title="SEO" open={false}><Field label="SEO slug" name="seoSlugMirror" defaultValue={product?.slug} hint="Uses the product slug above for now." /></FormSection>
    <FormSection title="Save / publish controls"><TextArea label="Owner note" name="auditNote" rows={3} />{product ? <Link className="btn btn-secondary md:w-fit" href={`/products/${product.slug}`}>Preview product page</Link> : null}<button className="btn btn-secondary md:w-fit" type="submit" name="intent" value="draft">Save draft</button><button className="btn btn-primary md:w-fit" type="submit" name="intent" value="continue">{product ? "Save and continue editing" : "Create product"}</button><button className="btn btn-primary md:w-fit" type="submit" name="intent" value="publish">Publish</button></FormSection>
  </form>;
}
