"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { AlertPanel } from "@/components/common/panels";
import { createProductAction, updateProductAction, type ProductActionState } from "@/lib/products/actions";
import { maxProductContentRows, maxProductFAQRows, maxProductFeatureRows, maxProductIncludedRows, maxProductMediaRows, maxProductSpecRows, productSectionKeys, productStatuses, restrictedClassOptions } from "@/lib/products/validation";
import type { AdminProductDetail } from "@/lib/products/service";

type Item<T> = T & { key: string; editing?: boolean; isNew?: boolean };

type MediaItem = Item<{ type: "IMAGE" | "YOUTUBE"; url?: string; thumbnailUrl?: string; alt?: string; title?: string }>;
type SectionItem = Item<{ sectionKey?: string; eyebrow?: string; title?: string; body?: string }>;
type FeatureItem = Item<{ code?: string; label?: string; value?: string; restrictedRelevant?: boolean }>;
type IncludedItem = Item<{ label?: string; description?: string; quantity?: number }>;
type SpecItem = Item<{ group?: string; label?: string; value?: string }>;
type FaqItem = Item<{ question?: string; answer?: string }>;

function Field({ label, name, defaultValue, type = "text", hint }: { label: string; name: string; defaultValue?: string | number; type?: string; hint?: string }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<input className="input" name={name} defaultValue={defaultValue ?? ""} type={type} />{hint ? <span className="text-xs font-medium text-slate-500">{hint}</span> : null}</label>;
}
function TextArea({ label, name, defaultValue, rows = 4 }: { label: string; name: string; defaultValue?: string; rows?: number }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<textarea className="input" rows={rows} name={name} defaultValue={defaultValue ?? ""} /></label>;
}
function Select({ label, name, defaultValue, values }: { label: string; name: string; defaultValue?: string; values: readonly string[] }) {
  return <label className="grid gap-2 text-sm font-bold text-slate-800">{label}<select className="input" name={name} defaultValue={defaultValue}>{values.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>;
}
function FormSection({ title, description, children, open = true }: { title: string; description?: string; children: React.ReactNode; open?: boolean }) {
  return <details className="card p-5" open={open}><summary className="cursor-pointer text-lg font-black text-slate-950">{title}</summary>{description ? <p className="mt-2 text-sm text-slate-600">{description}</p> : null}<div className="mt-5 grid gap-4 md:grid-cols-2">{children}</div></details>;
}

let newKey = 0;
function RepeatableList<T extends { key: string; editing?: boolean; isNew?: boolean }>({ title, help, addLabel, max, items, setItems, emptyLabel, makeItem, summary, children }: { title: string; help: string; addLabel: string; max: number; items: T[]; setItems: (items: T[]) => void; emptyLabel: string; makeItem: () => T; summary: (item: T, index: number) => string; children: (item: T, index: number) => React.ReactNode }) {
  const limitReached = items.length >= max;
  const move = (index: number, delta: number) => { const next = [...items]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setItems(next); };
  const remove = (index: number) => { const item = items[index]; if (!item.isNew && !window.confirm(`Remove ${summary(item, index)}? Existing saved items will be removed when you save the product.`)) return; setItems(items.filter((_, i) => i !== index)); };
  return <section className="grid gap-3 rounded-2xl border border-stone-200 p-4 md:col-span-2"><div><h3 className="font-black text-slate-950">{title}</h3><p className="text-sm text-slate-600">{help}</p></div>{items.length === 0 ? <p className="rounded-2xl bg-stone-50 p-4 text-sm font-bold text-slate-600">{emptyLabel}</p> : null}<div className="grid gap-3">{items.map((item, index) => <article className="rounded-2xl border border-stone-200 bg-white p-3" key={item.key}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{index + 1}. {summary(item, index)}</p><div className="flex flex-wrap gap-2"><button className="btn btn-secondary px-3 py-2" type="button" onClick={() => setItems(items.map((row, i) => i === index ? { ...row, editing: !row.editing } : row))}>{item.editing ? "Done" : "Edit"}</button><button className="btn btn-secondary px-3 py-2" type="button" disabled={index === 0} onClick={() => move(index, -1)}>Move up</button><button className="btn btn-secondary px-3 py-2" type="button" disabled={index === items.length - 1} onClick={() => move(index, 1)}>Move down</button><button className="btn btn-secondary px-3 py-2" type="button" onClick={() => remove(index)}>Remove</button></div></div>{item.editing ? <div className="mt-3 grid gap-3 md:grid-cols-2">{children(item, index)}</div> : null}</article>)}</div>{limitReached ? <p className="text-sm font-bold text-amber-700">Maximum reached: {max} items. Remove an item before adding another.</p> : <button className="btn btn-secondary w-fit" type="button" onClick={() => setItems([...items, makeItem()])}>{addLabel}</button>}</section>;
}

function MediaRows({ product }: { product?: AdminProductDetail }) {
  const [items, setItems] = useState<MediaItem[]>(() => (product?.media ?? []).map((m, i) => ({ key: `media-${i}`, type: m.type === "YOUTUBE" ? "YOUTUBE" : "IMAGE", url: m.url, thumbnailUrl: m.thumbnailUrl, alt: m.alt, title: m.title, editing: false })));
  return <RepeatableList title="Product media" help="Show only saved media here. Add an image upload/URL or a YouTube link; video file upload is not supported." addLabel="+ Add media" max={maxProductMediaRows} items={items} setItems={setItems} emptyLabel="No product media yet. Add media when you are ready." makeItem={(): MediaItem => ({ key: `new-media-${newKey++}`, type: "IMAGE", alt: product?.name, title: product?.name, editing: true, isNew: true })} summary={(item) => item.title || item.alt || (item.type === "YOUTUBE" ? "YouTube video" : "Image media")}>{(item, index) => <><input type="hidden" name={`mediaType${index}`} value={item.type} /><input type="hidden" name={`mediaSortOrder${index}`} value={index} /><label className="grid gap-2 text-sm font-bold text-slate-800">Media kind<select className="input" value={item.type} onChange={(event) => setItems(items.map((row) => row.key === item.key ? { ...row, type: event.target.value as "IMAGE" | "YOUTUBE" } : row))}><option value="IMAGE">Upload image</option><option value="YOUTUBE">Add YouTube video link</option></select></label>{item.type === "IMAGE" ? <label className="grid gap-2 text-sm font-bold text-slate-800">Image URL<input className="input" name={`mediaUrl${index}`} defaultValue={item.url ?? ""} /><span className="text-xs font-medium text-slate-500">Or upload a product image below.</span><input className="input" name={`mediaUpload${index}`} type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" /></label> : <Field label="YouTube video URL" name={`mediaYoutubeUrl${index}`} defaultValue={item.url} hint="Accepts youtube.com/watch?v=... and youtu.be/... links." />}<Field label="Thumbnail URL" name={`mediaThumbnailUrl${index}`} defaultValue={item.thumbnailUrl} /><Field label="Alt text" name={`mediaAlt${index}`} defaultValue={item.alt ?? product?.name} /><Field label="Title / aria label" name={`mediaTitle${index}`} defaultValue={item.title ?? product?.name} /></>}</RepeatableList>;
}

function ContentRows({ product }: { product?: AdminProductDetail }) {
  const [features, setFeatures] = useState<FeatureItem[]>(() => (product?.features ?? []).map((f, i) => ({ key: `feature-${i}`, ...f })));
  const [sections, setSections] = useState<SectionItem[]>(() => (product?.contentSections ?? []).map((s, i) => ({ key: `section-${i}`, ...s })));
  const [included, setIncluded] = useState<IncludedItem[]>(() => (product?.includedItems ?? []).map((row, i) => ({ key: `included-${i}`, ...row })));
  const [specs, setSpecs] = useState<SpecItem[]>(() => (product?.specs ?? []).map((row, i) => ({ key: `spec-${i}`, ...row })));
  const [faqs, setFaqs] = useState<FaqItem[]>(() => (product?.faqs ?? []).map((row, i) => ({ key: `faq-${i}`, ...row })));
  return <div className="grid gap-6 md:col-span-2"><TextArea label="Short description" name="description" defaultValue={product?.description} rows={3} />
    <RepeatableList title="Long description sections" help="Add, edit, remove, and reorder product page sections. Sort order is saved from this list." addLabel="+ Add content section" max={maxProductContentRows} items={sections} setItems={setSections} emptyLabel="No content sections yet." makeItem={() => ({ key: `new-section-${newKey++}`, sectionKey: "overview", title: product?.name ?? "Product section", editing: true, isNew: true })} summary={(item) => item.title || "Content section"}>{(item, index) => <><Select label="Section type" name={`sectionKey${index}`} defaultValue={item.sectionKey ?? "overview"} values={productSectionKeys} /><Field label="Title" name={`sectionTitle${index}`} defaultValue={item.title ?? product?.name} /><input type="hidden" name={`sectionSortOrder${index}`} value={index} /><Field label="Eyebrow" name={`sectionEyebrow${index}`} defaultValue={item.eyebrow} /><label className="grid gap-2 text-sm font-bold text-slate-800 md:col-span-2">Body<textarea className="input min-h-24" name={`sectionBody${index}`} defaultValue={item.body ?? ""} /></label></>}</RepeatableList>
    <RepeatableList title="Features" help="Short feature rows shown on product pages. Maximum 12." addLabel="+ Add feature" max={maxProductFeatureRows} items={features} setItems={setFeatures} emptyLabel="No features yet." makeItem={() => ({ key: `new-feature-${newKey++}`, editing: true, isNew: true })} summary={(item) => item.label || item.code || "Feature"}>{(item, index) => <><Field label="Internal code" name={`featureCode${index}`} defaultValue={item.code}/><Field label="Label" name={`featureLabel${index}`} defaultValue={item.label}/><Field label="Value" name={`featureValue${index}`} defaultValue={item.value}/><label className="flex items-end gap-2 pb-3 text-sm font-bold"><input defaultChecked={item.restrictedRelevant} name={`featureRestricted${index}`} type="checkbox" />Restricted review</label></>}</RepeatableList>
    <RepeatableList title="Included items" help="Items included with the product. Maximum 12." addLabel="+ Add included item" max={maxProductIncludedRows} items={included} setItems={setIncluded} emptyLabel="No included items yet." makeItem={() => ({ key: `new-included-${newKey++}`, quantity: 1, editing: true, isNew: true })} summary={(item) => item.label || "Included item"}>{(item, index) => <><Field label="Label" name={`includedLabel${index}`} defaultValue={item.label} /><Field label="Description" name={`includedDescription${index}`} defaultValue={item.description} /><Field label="Quantity" name={`includedQuantity${index}`} defaultValue={item.quantity ?? 1} type="number" /><input type="hidden" name={`includedSortOrder${index}`} value={index} /></>}</RepeatableList>
    <RepeatableList title="Specifications" help="Technical details and grouped specs. Maximum 30." addLabel="+ Add specification" max={maxProductSpecRows} items={specs} setItems={setSpecs} emptyLabel="No specifications yet." makeItem={() => ({ key: `new-spec-${newKey++}`, editing: true, isNew: true })} summary={(item) => item.label || "Specification"}>{(item, index) => <><Field label="Group" name={`specGroup${index}`} defaultValue={item.group} /><Field label="Label" name={`specLabel${index}`} defaultValue={item.label} /><Field label="Value" name={`specValue${index}`} defaultValue={item.value} /><input type="hidden" name={`specSortOrder${index}`} value={index} /></>}</RepeatableList>
    <RepeatableList title="FAQ" help="Questions and answers for the product page. Maximum 20." addLabel="+ Add FAQ" max={maxProductFAQRows} items={faqs} setItems={setFaqs} emptyLabel="No FAQs yet." makeItem={() => ({ key: `new-faq-${newKey++}`, editing: true, isNew: true })} summary={(item) => item.question || "FAQ"}>{(item, index) => <><Field label="Question" name={`faqQuestion${index}`} defaultValue={item.question} /><Field label="Answer" name={`faqAnswer${index}`} defaultValue={item.answer} /><input type="hidden" name={`faqSortOrder${index}`} value={index} /></>}</RepeatableList></div>;
}

export function ProductForm({ product, categories = [] }: { product?: AdminProductDetail; categories?: Array<{ id: string; name: string; slug: string }> }) {
  const [state, formAction] = useActionState<ProductActionState, FormData>(product ? updateProductAction : createProductAction, {});
  return <form action={formAction} encType="multipart/form-data" className="grid gap-6">{product ? <input name="id" type="hidden" value={product.id} /> : null}<AlertPanel title="Dangerous product changes require notes" tone="warning">Archive actions and restricted-status changes are audit logged. Use ARCHIVED instead of hard delete.</AlertPanel>{state.error ? <AlertPanel title="Product change blocked" tone="danger">{state.error}</AlertPanel> : null}{state.success ? <AlertPanel title="Product saved" tone="success">{state.success}</AlertPanel> : null}
    <FormSection title="Basic product info" description="Required identifiers and merchandising status stay at the top."><Field label="Name" name="name" defaultValue={product?.name} /><Field label="Slug" name="slug" defaultValue={product?.slug} /><Field label="SKU" name="sku" defaultValue={product?.sku} /><label className="grid gap-2 text-sm font-bold text-slate-800">Category<select className="input" name="categoryId" defaultValue={product?.categoryId ?? ""}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><Select label="Status" name="status" defaultValue={product?.status ?? "DRAFT"} values={productStatuses} /><Field label="Brand" name="brand" defaultValue={product?.brand ?? "Stun Fry"} /></FormSection>
    <FormSection title="Pricing and inventory"><Field label="Price" name="price" defaultValue={product?.price?.toFixed(2)} type="number" /><Field label="Stock quantity" name="stockQuantity" defaultValue={product?.stock ?? 0} type="number" /><Field label="Low stock threshold" name="lowStockThreshold" defaultValue={0} type="number" /></FormSection>
    <FormSection title="Compliance" description="Use STUN_GUN for stun-gun products; do not use legacy knuckle categories or restricted classes."><label className="flex items-center gap-2 text-sm font-bold"><input defaultChecked={product?.restricted} name="restricted" type="checkbox" />Restricted product</label><Select label="Restricted class" name="restrictedClass" defaultValue={product?.restrictedClass ?? "STUN_GUN"} values={restrictedClassOptions} /><AlertPanel title="Age and destination checks" tone="warning">Restricted products require the buyer to be at least 18 and pass state/destination verification at checkout. Existing compliance coverage is maintained by restricted class.</AlertPanel></FormSection>
    <FormSection title="Product media" description="Use one dynamic media list with Add, Edit, Remove, Move up, and Move down. Sort order is automatic." open={false}><MediaRows product={product} /></FormSection>
    <FormSection title="Product page content" description="Repeatable product content uses dynamic lists; normal single-value fields remain unchanged." open={false}><ContentRows product={product} /></FormSection>
    <FormSection title="SEO" open={false}><Field label="SEO slug" name="seoSlugMirror" defaultValue={product?.slug} hint="Uses the product slug above for now." /></FormSection>
    <FormSection title="Save / publish controls"><TextArea label="Owner note" name="auditNote" rows={3} />{product ? <Link className="btn btn-secondary md:w-fit" href={`/products/${product.slug}`}>Preview product page</Link> : null}<button className="btn btn-secondary md:w-fit" type="submit" name="intent" value="draft">Save draft</button><button className="btn btn-primary md:w-fit" type="submit" name="intent" value="continue">{product ? "Save and continue editing" : "Create product"}</button><button className="btn btn-primary md:w-fit" type="submit" name="intent" value="publish">Publish</button></FormSection>
  </form>;
}
